services:
  - type: web
    name: bot-trading-django
    runtime: python
    buildCommand: ""
    startCommand: gunicorn bot_trading_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bot_trading_project.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: nombre_de_tu_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
